-- Add aggregate columns for performance
ALTER TABLE "Book"
  ADD COLUMN IF NOT EXISTS "totalViews" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "ratingSum" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "ratingCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "ratingAvg" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Chapter"
  ADD COLUMN IF NOT EXISTS "totalViews" INTEGER NOT NULL DEFAULT 0;
